apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-09-21T19:25:09Z
  generation: 3
  labels:
    app: time-app-2
  name: time-app-2
  namespace: default
  resourceVersion: "1588"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/time-app-2
  uid: 0de48849-bdd4-11e8-a177-42010a9e0035
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-app-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: time-app-2
    spec:
      containers:
      - image: gcr.io/time-217118/github-wjsc-time:v1.0.1
        imagePullPolicy: IfNotPresent
        name: time
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-09-21T19:25:20Z
    lastUpdateTime: 2018-09-21T19:25:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
